// UNIFIED INLINE THEME STYLES
export const styles = {
  appRoot: { fontFamily: "'Inter', system-ui, -apple-system, sans-serif", backgroundColor: "#f8fafc", color: "#0f172a", minHeight: "100vh" },
  header: { height: "64px", backgroundColor: "#0b1329", color: "#ffffff", display: "flex", alignItems: "center", justifyContent: "space-between", padding: "0 20px", position: "fixed", top: 0, left: 0, right: 0, zIndex: 100, boxShadow: "0 4px 20px rgba(11, 19, 41, 0.15)", boxSizing: "border-box" },
  headerLeft: { display: "flex", alignItems: "center", gap: "12px" },
  brandBox: { width: "34px", height: "34px", background: "linear-gradient(135deg, #f59e0b, #d97706)", color: "#0b1329", fontWeight: "900", borderRadius: "8px", display: "flex", alignItems: "center", justifyContent: "center", boxShadow: "0 2px 8px rgba(245, 158, 11, 0.4)" },
  brandTitle: { fontWeight: "800", fontSize: "14px", color: "#fff", letterSpacing: "0.3px" },
  brandSub: { fontSize: "10px", color: "#f59e0b", fontWeight: "bold" },
  headerCenter: { flex: 1, maxWidth: "440px", margin: "0 20px" },
  searchInput: { width: "100%", padding: "8px 16px", background: "rgba(255,255,255,0.08)", border: "1px solid rgba(255,255,255,0.18)", borderRadius: "20px", color: "#fff", outline: "none", fontSize: "13px", transition: "all 0.2s", boxSizing: "border-box" },
  headerRight: { display: "flex", alignItems: "center", gap: "14px" },
  roleBadge: { background: "rgba(255,255,255,0.08)", padding: "4px 10px", borderRadius: "8px", fontSize: "11px", color: "#e2e8f0", display: "flex", alignItems: "center", gap: "8px", border: "1px solid rgba(255,255,255,0.15)" },
  roleSelectDropdown: { background: "#0f172a", color: "#f59e0b", border: "1px solid #f59e0b", padding: "3px 8px", borderRadius: "6px", fontSize: "11px", fontWeight: "bold", outline: "none", cursor: "pointer" },
  userAvatar: { width: "34px", height: "34px", color: "#fff", borderRadius: "50%", display: "flex", alignItems: "center", justifyContent: "center", fontWeight: "bold", fontSize: "13px", boxShadow: "0 2px 8px rgba(0,0,0,0.3)" },
  appLayout: { display: "flex", marginTop: "64px", minHeight: "calc(100vh - 64px)" },
  sidebar: { width: "240px", backgroundColor: "#ffffff", borderRight: "1px solid #e2e8f0", padding: "20px 12px", position: "fixed", top: "64px", bottom: 0, left: 0, display: "flex", flexDirection: "column", justifyContent: "space-between", gap: "20px", boxShadow: "2px 0 10px rgba(0,0,0,0.02)", boxSizing: "border-box" },
  sidebarSectionLabel: { fontSize: "11px", fontWeight: "800", color: "#94a3b8", marginBottom: "8px", letterSpacing: "0.5px" },
  sidebarNavItem: { padding: "10px 12px", borderRadius: "8px", fontWeight: "500", fontSize: "13px", color: "#475569", cursor: "pointer", display: "flex", justifyContent: "space-between", alignItems: "center", transition: "all 0.15s" },
  sidebarNavItemActive: { backgroundColor: "#eff6ff", color: "#2563eb", padding: "10px 12px", borderRadius: "8px", fontWeight: "bold", fontSize: "13px", cursor: "pointer", display: "flex", justifyContent: "space-between", alignItems: "center" },
  sidebarParentNav: { padding: "10px 12px", borderRadius: "8px", fontWeight: "600", fontSize: "13px", color: "#334155", cursor: "pointer", display: "flex", justifyContent: "space-between", alignItems: "center", backgroundColor: "#f8fafc", border: "1px solid #f1f5f9" },
  sidebarSubItem: { padding: "8px 12px", borderRadius: "6px", fontSize: "12px", fontWeight: "500", color: "#64748b", cursor: "pointer", transition: "background 0.15s" },
  sidebarSubItemActive: { padding: "8px 12px", borderRadius: "6px", fontSize: "12px", fontWeight: "bold", color: "#2563eb", backgroundColor: "#e0f2fe", cursor: "pointer" },
  sidebarFooter: { background: "#f8fafc", border: "1px solid #e2e8f0", borderRadius: "10px", padding: "12px" },
  mainContent: { flex: 1, marginLeft: "240px", padding: "24px", boxSizing: "border-box" },
  pageTopBar: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "20px" },
  breadcrumb: { fontSize: "12px", color: "#64748b", fontWeight: "500" },
  pageTitle: { fontSize: "20px", fontWeight: "800", color: "#0f172a", letterSpacing: "-0.3px" },
  dateBox: { background: "#0f172a", color: "#fff", padding: "6px 14px", borderRadius: "8px", fontSize: "12px", fontWeight: "bold", boxShadow: "0 2px 6px rgba(15,23,42,0.15)" },
  toolbar: { background: "#fff", border: "1px solid #cbd5e1", borderRadius: "10px", padding: "12px 16px", marginBottom: "16px", display: "flex", justifyContent: "space-between", alignItems: "center" },
  filterInput: { padding: "8px 12px", border: "1px solid #cbd5e1", borderRadius: "6px", fontSize: "13px", outline: "none", boxSizing: "border-box" },
  filterSelect: { padding: "8px 12px", border: "1px solid #cbd5e1", borderRadius: "6px", fontSize: "13px", outline: "none", boxSizing: "border-box" },
  tableWrap: { background: "#fff", border: "1px solid #cbd5e1", borderRadius: "10px", overflowX: "auto" },
  table: { width: "100%", borderCollapse: "collapse", fontSize: "13px", textAlign: "left" },
  thRow: { backgroundColor: "#f8fafc", borderBottom: "1px solid #cbd5e1" },
  th: { padding: "12px 14px", fontSize: "11px", fontWeight: "bold", color: "#475569" },
  tr: { borderBottom: "1px solid #f1f5f9" },
  td: { padding: "12px 14px" },
  pesertaClickable: { cursor: "pointer" },
  pesertaName: { fontWeight: "bold", color: "#1d4ed8", textDecoration: "underline" },
  pesertaSub: { fontSize: "11px", color: "#64748b" },
  badge: { background: "#dbeafe", color: "#1d4ed8", padding: "2px 8px", borderRadius: "4px", fontWeight: "bold", fontSize: "11px" },
  actionBtnIcon: { background: "#eff6ff", color: "#2563eb", border: "1px solid #bfdbfe", width: "32px", height: "32px", borderRadius: "6px", fontSize: "14px", display: "inline-flex", alignItems: "center", justifyContent: "center", cursor: "pointer", transition: "all 0.15s" },
  actionBtnParamIcon: { background: "#eff6ff", color: "#2563eb", border: "1px solid #bfdbfe", width: "34px", height: "34px", borderRadius: "8px", fontSize: "15px", display: "inline-flex", alignItems: "center", justifyContent: "center", cursor: "pointer", transition: "all 0.15s" },
  actionBtnHistoryIcon: { background: "#f8fafc", color: "#0f172a", border: "1px solid #cbd5e1", width: "34px", height: "34px", borderRadius: "8px", fontSize: "15px", display: "inline-flex", alignItems: "center", justifyContent: "center", cursor: "pointer", transition: "all 0.15s" },
  modalBackdrop: { position: "fixed", top: 0, left: 0, right: 0, bottom: 0, background: "rgba(15, 23, 42, 0.75)", zIndex: 1000, display: "flex", alignItems: "center", justifyContent: "center", padding: "20px", backdropFilter: "blur(4px)", boxSizing: "border-box" },
  modalContainer: { background: "#fff", width: "100%", maxWidth: "860px", borderRadius: "14px", overflow: "hidden", display: "flex", flexDirection: "column", maxHeight: "90vh", boxShadow: "0 25px 50px -12px rgba(0, 0, 0, 0.25)", boxSizing: "border-box" },
  modalHeader: { background: "#0b1329", color: "#fff", padding: "18px 24px", display: "flex", justifyContent: "space-between", alignItems: "center" },
  closeBtn: { background: "none", border: "none", color: "#fff", fontSize: "18px", cursor: "pointer" },
  modalTabBar: { display: "flex", background: "#f1f5f9", borderBottom: "2px solid #cbd5e1" },
  modalTabBtn: { padding: "12px 18px", background: "none", border: "none", fontSize: "12px", fontWeight: "bold", color: "#64748b", cursor: "pointer" },
  modalTabBtnActive: { padding: "12px 18px", background: "#fff", border: "none", borderBottom: "3px solid #2563eb", color: "#2563eb", fontWeight: "bold", fontSize: "12px", cursor: "pointer" },
  modalBody: { padding: "20px", overflowY: "auto", flex: 1 },
  bannerTitle: { background: "#e2e8f0", padding: "8px 14px", borderRadius: "6px", fontSize: "12px", fontWeight: "bold", color: "#334155", marginBottom: "12px" },
  stripeGrid: { border: "1px solid #dbeafe", borderRadius: "8px", overflow: "hidden" },
  stripeRow: { display: "flex", justifyContent: "space-between", padding: "9px 14px", fontSize: "13px" },
  pencilBtn: { background: "#eff6ff", border: "1px solid #bfdbfe", color: "#2563eb", padding: "3px 8px", borderRadius: "6px", cursor: "pointer", fontSize: "12px" },
  eyeBtn: { background: "#f1f5f9", border: "1px solid #cbd5e1", color: "#475569", padding: "3px 8px", borderRadius: "6px", cursor: "pointer", fontSize: "12px" },
  calcBox: { marginTop: "20px", background: "#f8fafc", border: "1px solid #cbd5e1", borderRadius: "10px", padding: "16px" },
  benefitCard: { background: "#fff", border: "1px solid #cbd5e1", borderRadius: "8px", padding: "12px" },
  totalBanner: { marginTop: "12px", background: "#0f172a", borderRadius: "8px", padding: "14px 18px", display: "flex", justifyContent: "space-between", alignItems: "center" },
  modalFooter: { padding: "16px 24px", background: "#f8fafc", borderTop: "1px solid #e2e8f0", display: "flex", justifyContent: "flex-end", gap: "12px" },
  secBtn: { padding: "9px 18px", background: "#e2e8f0", border: "none", borderRadius: "8px", fontWeight: "bold", fontSize: "13px", cursor: "pointer", color: "#475569" },
  priBtn: { padding: "9px 18px", background: "#2563eb", color: "#fff", border: "none", borderRadius: "8px", fontWeight: "bold", fontSize: "13px", cursor: "pointer" },
  btnPdfRed: { padding: "9px 20px", background: "linear-gradient(135deg, #dc2626, #b91c1c)", color: "#ffffff", border: "none", borderRadius: "8px", fontWeight: "bold", fontSize: "13px", cursor: "pointer", boxShadow: "0 4px 12px rgba(220, 38, 38, 0.25)" },
  btnExcelGreen: { padding: "9px 20px", background: "linear-gradient(135deg, #16a34a, #15803d)", color: "#ffffff", border: "none", borderRadius: "8px", fontWeight: "bold", fontSize: "13px", cursor: "pointer", boxShadow: "0 4px 12px rgba(22, 163, 74, 0.25)" },
  subModalContainer: { background: "#fff", width: "100%", maxWidth: "560px", borderRadius: "14px", overflow: "hidden", boxShadow: "0 20px 40px rgba(0,0,0,0.25)", boxSizing: "border-box" },
  subModalHeader: { background: "#0b1329", padding: "16px 20px", display: "flex", justifyContent: "space-between", alignItems: "center" },
  editInput: { width: "100%", padding: "10px 14px", border: "2px solid #60a5fa", borderRadius: "8px", fontSize: "14px", fontWeight: "bold", outline: "none", backgroundColor: "#f0f9ff", boxSizing: "border-box" },
  suffixText: { position: "absolute", right: "14px", fontWeight: "bold", color: "#64748b", fontSize: "12px", pointerEvents: "none" },
  toastWrap: { position: "fixed", bottom: "24px", right: "24px", zIndex: 2000, display: "flex", flexDirection: "column", gap: "8px" },
  toast: { background: "#0f172a", color: "#fff", padding: "12px 18px", borderRadius: "10px", fontSize: "13px", fontWeight: "bold", borderLeft: "4px solid #10b981", boxShadow: "0 10px 25px rgba(0,0,0,0.2)" },

  modernCardContainer: { background: "#ffffff", borderRadius: "14px", border: "1px solid #e2e8f0", padding: "20px", boxShadow: "0 4px 20px rgba(0,0,0,0.03)" },
  modernFilterCard: { border: "1px solid #cbd5e1", borderRadius: "12px", overflow: "hidden", boxShadow: "0 4px 14px rgba(0,0,0,0.04)" },
  modernFilterHeader: { background: "linear-gradient(135deg, #0b1329 0%, #1e293b 100%)", color: "#ffffff", padding: "14px 20px", fontSize: "13px", display: "flex", justifyContent: "space-between", alignItems: "center", cursor: "pointer", borderBottom: "1px solid rgba(255,255,255,0.08)" },
  modernFilterTag: { background: "rgba(255,255,255,0.12)", color: "#e2e8f0", padding: "3px 10px", borderRadius: "20px", fontSize: "11px", fontWeight: "600" },
  modernFilterBody: { padding: "20px", backgroundColor: "#ffffff" },
  modernControlsGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: "20px", marginBottom: "20px" },
  modernFieldGroup: { display: "flex", flexDirection: "column", gap: "6px" },
  modernLabel: { fontSize: "12px", fontWeight: "700", color: "#334155", display: "flex", alignItems: "center", gap: "6px" },
  modernInput: { padding: "10px 14px", border: "1px solid #cbd5e1", borderRadius: "8px", fontSize: "13px", outline: "none", transition: "all 0.2s", backgroundColor: "#f8fafc", fontWeight: "600", color: "#0f172a", boxSizing: "border-box" },
  modernSelect: { padding: "10px 14px", border: "1px solid #cbd5e1", borderRadius: "8px", fontSize: "13px", color: "#0f172a", backgroundColor: "#f8fafc", outline: "none", cursor: "pointer", fontWeight: "600", transition: "all 0.2s", boxSizing: "border-box" },
  modernActionBar: { display: "flex", alignItems: "center", paddingTop: "16px", borderTop: "1px solid #f1f5f9" },
  btnPrimaryModern: { background: "linear-gradient(135deg, #2563eb, #1d4ed8)", color: "#ffffff", border: "none", padding: "10px 22px", borderRadius: "8px", fontSize: "13px", fontWeight: "bold", cursor: "pointer", boxShadow: "0 4px 14px rgba(37, 99, 235, 0.3)", display: "inline-flex", alignItems: "center", gap: "8px", transition: "transform 0.15s, boxShadow 0.15s" },
  btnIconResetModern: { background: "#f1f5f9", color: "#475569", border: "1px solid #cbd5e1", width: "38px", height: "38px", borderRadius: "8px", fontSize: "15px", display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", transition: "all 0.15s" },
  thExcelExact: { border: "1px solid #000000", padding: "6px 8px", fontSize: "10px", fontWeight: "bold", backgroundColor: "#ffffff", color: "#0f172a" },
  tdExcelExact: { border: "1px solid #000000", padding: "5px 8px", fontSize: "10px", color: "#0f172a" }
};
